Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'price' isn't unique. You may not be able to reverse all URLs in this namespace
person.Person.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

System check identified 2 issues (0 silenced).
Not Found: /admin
[09/Apr/2020 06:24:29] "GET /admin HTTP/1.1" 404 1765
Not Found: /favicon.ico
[09/Apr/2020 06:24:30] "GET /favicon.ico HTTP/1.1" 404 1783
[09/Apr/2020 06:24:33] "GET /admin/ HTTP/1.1" 302 0
[09/Apr/2020 06:24:34] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1913
[09/Apr/2020 06:24:34] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[09/Apr/2020 06:24:50] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1913
Forbidden: /api/vehicle_type/list_create/
[09/Apr/2020 06:25:19] "GET /api/vehicle_type/list_create/ HTTP/1.1" 403 5177
[09/Apr/2020 06:27:07] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[09/Apr/2020 06:27:08] "GET /admin/ HTTP/1.1" 200 23744
[09/Apr/2020 06:27:11] "GET /api/vehicle_type/list_create/ HTTP/1.1" 200 9632
[09/Apr/2020 06:27:23] "GET /api/vehicle_model/list_create/ HTTP/1.1" 200 12064
[09/Apr/2020 06:27:41] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 9432
Not Found: /api/vehicle_mark/update_delete/
[09/Apr/2020 06:33:21] "GET /api/vehicle_mark/update_delete/ HTTP/1.1" 404 1842
[09/Apr/2020 06:33:24] "GET /api/vehicle_mark/update_delete/2 HTTP/1.1" 200 10355
Not Found: /api/vehicle_mark/update_delete/200
[09/Apr/2020 06:40:44] "GET /api/vehicle_mark/update_delete/200 HTTP/1.1" 404 10061
Forbidden: /api/vehicle_mark/list_create/
[09/Apr/2020 20:30:15] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 403 5177
[09/Apr/2020 20:30:15] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 200 817
[09/Apr/2020 20:30:15] "GET /static/rest_framework/css/default.css HTTP/1.1" 200 1131
[09/Apr/2020 20:30:15] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 200 3385
[09/Apr/2020 20:30:15] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 200 121457
[09/Apr/2020 20:30:15] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 200 3597
[09/Apr/2020 20:30:15] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 200 88145
[09/Apr/2020 20:30:15] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 200 1719
[09/Apr/2020 20:30:15] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 200 39680
[09/Apr/2020 20:30:15] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 200 13632
[09/Apr/2020 20:30:15] "GET /static/rest_framework/js/default.js HTTP/1.1" 200 1268
[09/Apr/2020 20:30:15] "GET /static/rest_framework/img/grid.png HTTP/1.1" 200 1458
Not Found: /favicon.ico
[09/Apr/2020 20:30:15] "GET /favicon.ico HTTP/1.1" 404 1783
Not Found: /admin
[09/Apr/2020 20:31:09] "GET /admin HTTP/1.1" 404 1765
[09/Apr/2020 20:31:24] "GET /admin/ HTTP/1.1" 302 0
[09/Apr/2020 20:31:24] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1913
[09/Apr/2020 20:31:24] "GET /static/admin/css/login.css HTTP/1.1" 200 1233
[09/Apr/2020 20:31:24] "GET /static/admin/css/base.css HTTP/1.1" 200 16378
[09/Apr/2020 20:31:24] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18052
[09/Apr/2020 20:31:24] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[09/Apr/2020 20:31:24] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[09/Apr/2020 20:31:24] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[09/Apr/2020 20:31:33] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 2074
[09/Apr/2020 20:31:33] "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[09/Apr/2020 20:31:42] "POST /admin/login/?next=/admin/ HTTP/1.1" 200 2074
[09/Apr/2020 20:31:47] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[09/Apr/2020 20:31:48] "GET /admin/ HTTP/1.1" 200 23744
[09/Apr/2020 20:31:48] "GET /static/admin/css/dashboard.css HTTP/1.1" 200 412
[09/Apr/2020 20:31:48] "GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
[09/Apr/2020 20:31:48] "GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
[09/Apr/2020 20:32:00] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 9432
Forbidden: /api/vehicle_mark/list_create/
[09/Apr/2020 20:33:02] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 403 58
Forbidden: /api/vehicle_mark/list_create/
[09/Apr/2020 20:33:51] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 403 58
Forbidden: /api/vehicle_mark/list_create/
[09/Apr/2020 20:34:25] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 403 58
[09/Apr/2020 20:34:58] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 9432
[09/Apr/2020 20:35:01] "OPTIONS /api/vehicle_mark/list_create/ HTTP/1.1" 200 10229
[09/Apr/2020 20:35:07] "OPTIONS /api/vehicle_mark/list_create/ HTTP/1.1" 200 10229
[09/Apr/2020 20:35:08] "OPTIONS /api/vehicle_mark/list_create/ HTTP/1.1" 200 10229
[09/Apr/2020 20:35:14] "GET /api/vehicle_mark/list_create/?format=api HTTP/1.1" 200 9498
Forbidden: /api/vehicle_mark/list_create/
[09/Apr/2020 20:35:40] "GET /api/vehicle_mark/list_create/?format=api HTTP/1.1" 403 5210
Forbidden: /api/vehicle_mark/list_create/
[09/Apr/2020 20:35:46] "GET /api/vehicle_mark/list_create/?format=api HTTP/1.1" 403 5210
[09/Apr/2020 20:35:56] "GET /api/vehicle_mark/list_create/?format=api HTTP/1.1" 200 9498
[09/Apr/2020 20:36:19] "GET /api/vehicle_mark/list_create/?format=json HTTP/1.1" 200 335
Forbidden: /api/vehicle_mark/list_create/
[09/Apr/2020 20:36:37] "GET /api/vehicle_mark/list_create/?format=json HTTP/1.1" 403 58
Forbidden: /api/vehicle_mark/list_create/
[09/Apr/2020 20:36:42] "GET /api/vehicle_mark/list_create/?format=json HTTP/1.1" 403 58
Forbidden: /api/vehicle_mark/list_create/
[09/Apr/2020 20:40:36] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 403 58
Forbidden: /api/vehicle_mark/list_create/
[09/Apr/2020 20:40:39] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 403 58
[09/Apr/2020 20:40:45] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 9432
Forbidden: /api/vehicle_mark/list_create/
[09/Apr/2020 20:41:23] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 403 58
Forbidden: /api/vehicle_mark/list_create/
[10/Apr/2020 05:02:16] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 403 58
Forbidden: /api/vehicle_mark/list_create/
[10/Apr/2020 05:32:29] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 403 58
Forbidden: /api/vehicle_mark/list_create/
[10/Apr/2020 05:33:57] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 403 5177
Not Found: /favicon.ico
[10/Apr/2020 05:33:57] "GET /favicon.ico HTTP/1.1" 404 1783
[10/Apr/2020 05:34:07] "GET /admin/ HTTP/1.1" 302 0
[10/Apr/2020 05:34:07] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1913
[10/Apr/2020 05:34:14] "POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
[10/Apr/2020 05:34:14] "GET /admin/ HTTP/1.1" 200 23744
[10/Apr/2020 05:34:17] "GET /admin/login/?next=/admin/ HTTP/1.1" 302 0
[10/Apr/2020 05:34:17] "GET /admin/ HTTP/1.1" 200 23744
[10/Apr/2020 05:34:20] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 9432
Forbidden: /api/vehicle_mark/list_create/
[10/Apr/2020 05:34:28] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 403 58
Forbidden: /api/vehicle_mark/list_create/
[10/Apr/2020 05:34:37] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 403 58
Forbidden: /api/vehicle_mark/list_create/
[10/Apr/2020 05:36:21] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 403 58
Forbidden: /api/vehicle_mark/list_create/
[10/Apr/2020 05:58:11] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 403 58
/home/user/projects/aplusa_management_dev/aplusa_management/permissions.py changed, reloading.
Performing system checks...

April 09, 2020 - 06:24:17
Django version 3.0.3, using settings 'aplusa_management.settings'
Starting development server at http://0.0.0.0:8010/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/projects/aplusa_management_dev/aplusa_management/urls.py", line 26, in <module>
    path('api/vehicle_type/', include('vehicle_type.api.urls')),
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/projects/aplusa_management_dev/vehicle_type/api/urls.py", line 2, in <module>
    from vehicle_type.api.views import VehicleTypeListCreateAPIView,VehicleTypeUpdateDeleteAPIView
  File "/home/user/projects/aplusa_management_dev/vehicle_type/api/views.py", line 4, in <module>
    from aplusa_management.permissions import CustomDjangoModelPermissions
  File "/home/user/projects/aplusa_management_dev/aplusa_management/permissions.py", line 4
    # self.perms_map['GET'] = ['%(app_label)s.view_%(model_name)s']
                                                                  ^
SyntaxError: unexpected EOF while parsing

/home/user/projects/aplusa_management_dev/aplusa_management/permissions.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'price' isn't unique. You may not be able to reverse all URLs in this namespace
person.Person.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

System check identified 2 issues (0 silenced).
Internal Server Error: /api/vehicle_mark/list_create/
Traceback (most recent call last):
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
    response = self.handle_exception(exc)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
    raise exc
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/rest_framework/views.py", line 493, in dispatch
    self.initial(request, *args, **kwargs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/rest_framework/views.py", line 411, in initial
    self.check_permissions(request)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/rest_framework/views.py", line 331, in check_permissions
    for permission in self.get_permissions():
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/rest_framework/views.py", line 278, in get_permissions
    return [permission() for permission in self.permission_classes]
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/rest_framework/views.py", line 278, in <listcomp>
    return [permission() for permission in self.permission_classes]
TypeError: __init__() should return None, not 'bool'
[10/Apr/2020 06:00:20] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 500 17125
/home/user/projects/aplusa_management_dev/aplusa_management/permissions.py changed, reloading.
Performing system checks...

April 10, 2020 - 06:00:19
Django version 3.0.3, using settings 'aplusa_management.settings'
Starting development server at http://0.0.0.0:8010/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'price' isn't unique. You may not be able to reverse all URLs in this namespace
person.Person.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

System check identified 2 issues (0 silenced).
/home/user/projects/aplusa_management_dev/aplusa_management/permissions.py changed, reloading.
Performing system checks...

April 10, 2020 - 06:00:35
Django version 3.0.3, using settings 'aplusa_management.settings'
Starting development server at http://0.0.0.0:8010/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'price' isn't unique. You may not be able to reverse all URLs in this namespace
person.Person.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

System check identified 2 issues (0 silenced).
/home/user/projects/aplusa_management_dev/aplusa_management/permissions.py changed, reloading.
Performing system checks...

April 10, 2020 - 06:05:02
Django version 3.0.3, using settings 'aplusa_management.settings'
Starting development server at http://0.0.0.0:8010/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/projects/aplusa_management_dev/aplusa_management/urls.py", line 26, in <module>
    path('api/vehicle_type/', include('vehicle_type.api.urls')),
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/projects/aplusa_management_dev/vehicle_type/api/urls.py", line 2, in <module>
    from vehicle_type.api.views import VehicleTypeListCreateAPIView,VehicleTypeUpdateDeleteAPIView
  File "/home/user/projects/aplusa_management_dev/vehicle_type/api/views.py", line 4, in <module>
    from aplusa_management.permissions import CustomDjangoModelPermissions
  File "/home/user/projects/aplusa_management_dev/aplusa_management/permissions.py", line 1, in <module>
    from rest_framework.permissions import BasePermisson
ImportError: cannot import name 'BasePermisson'

/home/user/projects/aplusa_management_dev/aplusa_management/permissions.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/urls/resolvers.py", line 407, in check
    for pattern in self.url_patterns:
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/urls/resolvers.py", line 588, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/urls/resolvers.py", line 581, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/projects/aplusa_management_dev/aplusa_management/urls.py", line 26, in <module>
    path('api/vehicle_type/', include('vehicle_type.api.urls')),
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/projects/aplusa_management_dev/vehicle_type/api/urls.py", line 2, in <module>
    from vehicle_type.api.views import VehicleTypeListCreateAPIView,VehicleTypeUpdateDeleteAPIView
  File "/home/user/projects/aplusa_management_dev/vehicle_type/api/views.py", line 4, in <module>
    from aplusa_management.permissions import CustomDjangoModelPermissions
  File "/home/user/projects/aplusa_management_dev/aplusa_management/permissions.py", line 1, in <module>
    from rest_framework.permissions import BasePermisson
ImportError: cannot import name 'BasePermisson'

/home/user/projects/aplusa_management_dev/aplusa_management/permissions.py changed, reloading.
Performing system checks...

Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'price' isn't unique. You may not be able to reverse all URLs in this namespace
person.Person.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

System check identified 2 issues (0 silenced).
[10/Apr/2020 06:08:52] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 9398
[10/Apr/2020 06:08:52] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[10/Apr/2020 06:08:52] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[10/Apr/2020 06:08:52] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[10/Apr/2020 06:08:52] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[10/Apr/2020 06:08:52] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[10/Apr/2020 06:08:52] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[10/Apr/2020 06:08:52] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[10/Apr/2020 06:08:52] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[10/Apr/2020 06:08:52] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[10/Apr/2020 06:08:52] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[10/Apr/2020 06:08:52] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
Not Found: /favicon.ico
[10/Apr/2020 06:08:53] "GET /favicon.ico HTTP/1.1" 404 1783
[10/Apr/2020 06:08:56] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
/home/user/projects/aplusa_management_dev/aplusa_management/permissions.py changed, reloading.
Performing system checks...

April 10, 2020 - 06:08:50
Django version 3.0.3, using settings 'aplusa_management.settings'
Starting development server at http://0.0.0.0:8010/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'price' isn't unique. You may not be able to reverse all URLs in this namespace
person.Person.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

System check identified 2 issues (0 silenced).
[10/Apr/2020 06:09:13] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 9398
[10/Apr/2020 06:09:16] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 9398
[10/Apr/2020 06:09:17] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 9398
[10/Apr/2020 06:09:20] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:09:22] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:09:45] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:10:01] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:10:18] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 9398
/home/user/projects/aplusa_management_dev/aplusa_management/permissions.py changed, reloading.
Performing system checks...

April 10, 2020 - 06:09:11
Django version 3.0.3, using settings 'aplusa_management.settings'
Starting development server at http://0.0.0.0:8010/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'price' isn't unique. You may not be able to reverse all URLs in this namespace
person.Person.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

System check identified 2 issues (0 silenced).
[10/Apr/2020 06:11:38] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 9398
[10/Apr/2020 06:12:42] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:12:48] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:17:45] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:18:17] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:19:12] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:19:21] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:20:11] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:20:46] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:20:49] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:21:59] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:22:02] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:22:06] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:22:42] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:22:47] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:23:12] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
Not Found: /api/vehicle_mark/list_create/'
[10/Apr/2020 06:24:35] "GET /api/vehicle_mark/list_create/' HTTP/1.1" 404 1855
Not Found: /api/vehicle_mark/list_create/'
[10/Apr/2020 06:25:04] "GET /api/vehicle_mark/list_create/' HTTP/1.1" 404 1855
Not Found: /api/vehicle_mark/list_create/'
[10/Apr/2020 06:25:07] "GET /api/vehicle_mark/list_create/' HTTP/1.1" 404 1855
Not Found: /api/vehicle_mark/list_create/'
[10/Apr/2020 06:25:28] "GET /api/vehicle_mark/list_create/' HTTP/1.1" 404 1855
Not Found: /api/vehicle_mark/list_create/'
[10/Apr/2020 06:25:46] "GET /api/vehicle_mark/list_create/' HTTP/1.1" 404 1855
Not Found: /api/vehicle_mark/list_create/'
[10/Apr/2020 06:25:58] "GET /api/vehicle_mark/list_create/' HTTP/1.1" 404 1855
Not Found: /api/vehicle_mark/list_create/'
[10/Apr/2020 06:26:05] "GET /api/vehicle_mark/list_create/' HTTP/1.1" 404 1855
[10/Apr/2020 06:26:44] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:27:13] code 400, message Bad request version ('K«\x9c\x86#ÞËÚ°\x92z2Ó')
[10/Apr/2020 06:27:13] You're accessing the development server over HTTPS, but it only supports HTTP.

[10/Apr/2020 06:27:13] code 400, message Bad request version ('P\x90êF@db\x9e\x87\x9cÌÌ-²â00¶Î\x00I@9þ¿sÍ:Ö\x05¹\x00"ZZ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[10/Apr/2020 06:27:13] You're accessing the development server over HTTPS, but it only supports HTTP.

[10/Apr/2020 06:28:50] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\x8dcH\x0eÇ\x0bÖá\x8erïëÆ\'æÿä SvB\x0fËé\x14ßèËûfÁÂ Â\t»õÔ\x85¹o¥\x99ñþ\x82.F\x96\x17åÆ×\x1b©¿Ú¡(-=Áû½{\x00"úú\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[10/Apr/2020 06:28:50] You're accessing the development server over HTTPS, but it only supports HTTP.

[10/Apr/2020 06:31:29] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:34:31] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:36:39] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:36:47] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03±\x19`\x01\x85¬\x10!Ìz\'\x86SI¨à`\x90%«½\x1eÄ\\\x9as\x07Ô\x00Ð\rø )\xa0~Í\x97fJ\x96\x11°\x97[\x1d\x0b<VXÔ¹\tò\x19F¨$\x84Pob,&|\x00"JJ\x13\x01\x13\x02\x13\x03À+À/À,À0Ì©Ì¨À\x13À\x14\x00\x9c\x00\x9d\x00/\x005\x00')
[10/Apr/2020 06:36:47] You're accessing the development server over HTTPS, but it only supports HTTP.

[10/Apr/2020 06:37:09] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:38:04] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:39:23] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:39:31] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:39:33] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:40:22] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:40:31] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:41:12] code 400, message Bad request syntax ('\x16\x03\x01\x02\x00\x01\x00\x01ü\x03\x03\tV\x9e,W\x12\x9a,\r\x87Re^ö^²½tc¤$¬\x16)½à\x8e\x18\x90\x9d>\x80 ì\x08*W\x9f\x19d-}\x14\x00¬r\x006\x8eô\x1f·\x81ýÈ·\x82\x12\x1eßÞ')
[10/Apr/2020 06:41:12] You're accessing the development server over HTTPS, but it only supports HTTP.

[10/Apr/2020 06:42:13] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:46:35] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:48:36] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:51:36] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:51:39] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:51:58] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:52:35] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:54:36] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:54:56] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:56:06] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:56:45] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:57:20] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:57:48] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:57:51] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:58:13] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:58:31] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 06:59:01] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 07:01:51] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 07:02:50] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 07:03:53] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 07:04:20] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 07:05:13] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 07:08:22] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 07:11:07] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 07:11:31] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 07:11:36] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 07:11:45] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
/home/user/projects/aplusa_management_dev/aplusa_management/settings.py changed, reloading.
Performing system checks...

April 10, 2020 - 06:11:35
Django version 3.0.3, using settings 'aplusa_management.settings'
Starting development server at http://0.0.0.0:8010/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'price' isn't unique. You may not be able to reverse all URLs in this namespace
person.Person.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

System check identified 2 issues (0 silenced).
/home/user/projects/aplusa_management_dev/aplusa_management/settings.py changed, reloading.
Performing system checks...

April 10, 2020 - 07:31:34
Django version 3.0.3, using settings 'aplusa_management.settings'
Starting development server at http://0.0.0.0:8010/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'price' isn't unique. You may not be able to reverse all URLs in this namespace
person.Person.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

System check identified 2 issues (0 silenced).
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 45, in get_internal_wsgi_application
    return import_string(app_path)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/user/projects/aplusa_management_dev/aplusa_management/wsgi.py", line 16, in <module>
    application = get_wsgi_application()
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 127, in __init__
    self.load_middleware()
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/handlers/base.py", line 35, in load_middleware
    middleware = import_string(middleware_path)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'corsheaders.middleware.CorsMiddlewaredjango'; 'corsheaders.middleware' is not a package

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/utils/autoreload.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 137, in inner_run
    handler = self.get_handler(*args, **options)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 64, in get_handler
    return get_internal_wsgi_application()
  File "/home/user/virtual_environments/aplusa_management/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 50, in get_internal_wsgi_application
    ) from err
django.core.exceptions.ImproperlyConfigured: WSGI application 'aplusa_management.wsgi.application' could not be loaded; Error importing module.

/home/user/projects/aplusa_management_dev/aplusa_management/settings.py changed, reloading.
Performing system checks...

April 10, 2020 - 07:32:20
Django version 3.0.3, using settings 'aplusa_management.settings'
Starting development server at http://0.0.0.0:8010/
Quit the server with CONTROL-C.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'price' isn't unique. You may not be able to reverse all URLs in this namespace
person.Person.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

System check identified 2 issues (0 silenced).
Watching for file changes with StatReloader
System check identified some issues:

WARNINGS:
?: (urls.W005) URL namespace 'price' isn't unique. You may not be able to reverse all URLs in this namespace
person.Person.user: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
	HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.

System check identified 2 issues (0 silenced).
[10/Apr/2020 07:53:18] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 9398
[10/Apr/2020 07:53:49] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 07:53:53] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 07:54:53] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 07:57:48] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 07:59:10] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[10/Apr/2020 08:08:31] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[11/Apr/2020 12:38:55] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[11/Apr/2020 12:39:46] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 9432
[13/Apr/2020 05:22:58] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 05:33:05] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 09:02:55] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 10:14:42] "GET /api/vehicle_type/list_create/ HTTP/1.1" 200 9598
Not Found: /favicon.ico
[13/Apr/2020 10:14:42] "GET /favicon.ico HTTP/1.1" 404 1783
Not Found: /api/vehicle_type/list_create2/
[13/Apr/2020 10:14:46] "GET /api/vehicle_type/list_create2/ HTTP/1.1" 404 1839
[13/Apr/2020 10:14:56] "GET /api/vehicle_type/list_create/ HTTP/1.1" 200 9598
Not Found: /api/vehicle_types/list_create/
[13/Apr/2020 10:15:08] "GET /api/vehicle_types/list_create/ HTTP/1.1" 404 1839
[13/Apr/2020 10:15:19] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 9398
[13/Apr/2020 10:15:19] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 9398
[13/Apr/2020 12:15:33] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 12:56:16] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 13:13:06] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 13:20:56] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 13:20:56] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 13:29:29] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 13:29:39] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 13:55:59] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 13:55:59] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 13:59:03] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 13:59:03] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 14:00:07] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 14:00:07] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 14:04:17] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[13/Apr/2020 14:04:18] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
[14/Apr/2020 13:24:37] "GET /api/vehicle_mark/list_create/ HTTP/1.1" 200 335
Not Found: /admin
[15/Apr/2020 05:55:23] "GET /admin HTTP/1.1" 404 1765
Not Found: /favicon.ico
[15/Apr/2020 05:55:24] "GET /favicon.ico HTTP/1.1" 404 1783
[15/Apr/2020 05:55:29] "GET /admin/ HTTP/1.1" 302 0
[15/Apr/2020 05:55:29] "GET /admin/login/?next=/admin/ HTTP/1.1" 200 1913
[15/Apr/2020 05:55:29] "GET /static/admin/css/login.css HTTP/1.1" 200 1233
[15/Apr/2020 05:55:29] "GET /static/admin/css/responsive.css HTTP/1.1" 200 18052
[15/Apr/2020 05:55:29] "GET /static/admin/css/base.css HTTP/1.1" 304 0
[15/Apr/2020 05:55:29] "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
[15/Apr/2020 05:55:30] "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[15/Apr/2020 05:55:30] "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[15/Apr/2020 11:48:14] "GET /api/vehicle_type/list_create/ HTTP/1.1" 200 9598
[15/Apr/2020 11:48:14] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[15/Apr/2020 11:48:14] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[15/Apr/2020 11:48:14] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[15/Apr/2020 11:48:14] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[15/Apr/2020 11:48:14] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[15/Apr/2020 11:48:14] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[15/Apr/2020 11:48:14] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[15/Apr/2020 11:48:14] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[15/Apr/2020 11:48:14] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[15/Apr/2020 11:48:14] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
[15/Apr/2020 11:48:14] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
Not Found: /favicon.ico
[15/Apr/2020 11:48:14] "GET /favicon.ico HTTP/1.1" 404 1783
[20/Apr/2020 11:24:49] "GET /api/vehicle_type/list_create/ HTTP/1.1" 200 9598
[20/Apr/2020 11:24:49] "GET /static/rest_framework/css/bootstrap.min.css HTTP/1.1" 304 0
[20/Apr/2020 11:24:49] "GET /static/rest_framework/css/bootstrap-tweaks.css HTTP/1.1" 304 0
[20/Apr/2020 11:24:49] "GET /static/rest_framework/css/prettify.css HTTP/1.1" 304 0
[20/Apr/2020 11:24:49] "GET /static/rest_framework/css/default.css HTTP/1.1" 304 0
[20/Apr/2020 11:24:50] "GET /static/rest_framework/js/csrf.js HTTP/1.1" 304 0
[20/Apr/2020 11:24:50] "GET /static/rest_framework/js/prettify-min.js HTTP/1.1" 304 0
[20/Apr/2020 11:24:50] "GET /static/rest_framework/js/default.js HTTP/1.1" 304 0
[20/Apr/2020 11:24:50] "GET /static/rest_framework/js/bootstrap.min.js HTTP/1.1" 304 0
[20/Apr/2020 11:24:50] "GET /static/rest_framework/img/grid.png HTTP/1.1" 304 0
[20/Apr/2020 11:24:51] "GET /static/rest_framework/js/jquery-3.4.1.min.js HTTP/1.1" 304 0
[20/Apr/2020 11:24:52] "GET /static/rest_framework/js/ajax-form.js HTTP/1.1" 304 0
Not Found: /favicon.ico
[20/Apr/2020 11:24:52] "GET /favicon.ico HTTP/1.1" 404 1783
